services:
  mysql:
    image: mysql:8.4
    container_name: betwise-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: betwise
      MYSQL_USER: betwise
      MYSQL_PASSWORD: betwisepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: betwise-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: